### ISSUE TITLE
Bump to Sanity Studio v3

### ISSUE THREAD

**Issue by slavakurilyak** [pcbowers/sanity-plugin-tags#17]
It would be great to see this plugin be compatible with Sanity Studio v3

**Comment by aleksanderanwar** [comment]
@pcbowers Is this something you will get around to soon, or should we start looking for other alternatives? :)

**Comment by pcbowers** [comment]
@aleksanderanwar Thanks for bumping this! I was using sanity for a side project back in April, and haven't done a great job of maintenance with this since then as I've taken a new job that eats a lot of my hours and I haven't had the time I've wanted to bump this. I'll take another look in my free time though, and if you want to put in a PR, go ahead!

**Comment by LeoBakerHytch** [comment]
Going to give it a go upgrading this to v3.

**Comment by LeoBakerHytch** [comment]
Good to go: #19  😄

**Comment by pcbowers** [comment]
Fixed with #19
